name: main

on:
  push:
    branches:
      - main
      - "release/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup netcoreapp3.1 (unit testing)
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal

  gitversion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: git fetch
        run: git fetch --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: Determine GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $GITVERSION_SEMVER
          release_name: Release $GITVERSION_SEMVER
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - To do: changelog
          draft: true
          prerelease: startsWith(${GITHUB_REF##*/}, 'release/')
